-- MySQL Script generated by MySQL Workbench
-- Wed Apr 23 22:47:32 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`particorpo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`particorpo` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descrizione` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `descrizione_UNIQUE` (`descrizione` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`esami`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`esami` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `CodiceMinisteriale` VARCHAR(10) NOT NULL,
  `CodiceInterno` VARCHAR(10) NOT NULL,
  `DescrizioneEsame` VARCHAR(100) NULL,
  `particorpo_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `particorpo_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `CodiceMinisteriale_UNIQUE` (`CodiceMinisteriale` ASC) VISIBLE,
  UNIQUE INDEX `CodiceInterno_UNIQUE` (`CodiceInterno` ASC) VISIBLE,
  INDEX `fk_esami_particorpo1_idx` (`particorpo_id` ASC) VISIBLE,
  CONSTRAINT `fk_esami_particorpo1`
    FOREIGN KEY (`particorpo_id`)
    REFERENCES `mydb`.`particorpo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ambulatori`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ambulatori` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ambulatori_esami`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ambulatori_esami` (
  `ambulatori_id` INT UNSIGNED NOT NULL,
  `esami_id` INT NOT NULL,
  PRIMARY KEY (`ambulatori_id`, `esami_id`),
  INDEX `fk_ambulatori_has_esami_esami1_idx` (`esami_id` ASC) VISIBLE,
  INDEX `fk_ambulatori_has_esami_ambulatori_idx` (`ambulatori_id` ASC) VISIBLE,
  CONSTRAINT `fk_ambulatori_has_esami_ambulatori`
    FOREIGN KEY (`ambulatori_id`)
    REFERENCES `mydb`.`ambulatori` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ambulatori_has_esami_esami1`
    FOREIGN KEY (`esami_id`)
    REFERENCES `mydb`.`esami` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
